server:
  address:     ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

logger:
  level : "all"
  stdout: true

database:
  default:
    link: "mysql:root:@tcp(127.0.0.1:3306)/gftest"
    timezone: "Asia/Shanghai"
    debug: false

